services:
  - type: web
    name: jnvbgk-alumni
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://mahadev:ka039814@cluster0.tiauwuh.mongodb.net/jnv_alumni
      - key: JWT_SECRET
        value: jnv-alumni-secret-key-2024
      - key: PORT
        value: 5000
      - key: CORS_ORIGIN
        value: https://frolicking-moonbeam-d09148.netlify.app
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1